networks:
    default:
        name: expert-finder-network
        external: true
services:
    expert-finder-backend:
        image: expert-finder-backend
        container_name: expert-finder-backend
        ports:
            - "8000:8000"
        volumes:    
            - ../../secrets:/secrets
            - .:/app
            - ../../google-scholar-data:/google-scholar-data
            - ../../chromadb:/chromadb
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /secrets/expertfinder.json
            GCP_PROJECT: $GCP_PROJECT
            DATA_DIR: $DATA_DIR
            SECRETS_DIR: /secrets
            BASE_DIR: $BASE_DIR
            OPENAI_API_KEY: $OPENAI_API_KEY
            PERSISTENT_DIR: $PERSISTENT_DIR
