networks:
    default:
        name: expert-finder-network
        external: true
services:
    expert-finder:
        image: expert-finder
        container_name: expert-finder
        volumes:    
            - ../../secrets:/secrets
            - ../../ExpertFinder:/app
            - ../../google-scholar-data:/google-scholar-data
            - ../../chromadb:/chromadb
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            DATA_DIR: $DATA_DIR
            SECRETS_DIR: $SECRETS_DIR
            BASE_DIR: $BASE_DIR
            PERSISTENT_DIR: $PERSISTENT_DIR
