"""
List of keywords used in LinkedIn searches for AI/ML professionals.
Each item is a string containing related keyword pairs.
"""

# keywords_list = [
#     "machine learning deep learning",
#     "pytorch keras",
#     "quantization pruning",
#     "precision-recall F1 score",
#     "ensemble methods transfer learning",
#     "artificial intelligence natural language processing",
#     "overfitting underfitting",
#     "image recognition object detection",
#     "autoencoders LSTM",
#     "keras scikit-learn",
#     "explainable AI ethical AI",
#     "few-shot learning zero-shot learning",
#     "decision trees ensemble methods",
#     "reinforcement learning supervised learning",
#     "recurrent neural networks transformers",
#     "zero-shot learning meta-learning",
#     "supervised learning unsupervised learning",
#     "multi-task learning multi-modal learning",
#     "neural networks artificial intelligence",
#     "dimensionality reduction random forests",
#     "quantum machine learning edge AI",
#     "domain adaptation self-supervised learning",
#     "semantic segmentation generative models",
#     "exploratory data analysis data cleaning",
#     "computer vision reinforcement learning",
#     "object detection semantic segmentation",
#     "gradient descent backpropagation",
#     "confusion matrix ROC curve",
#     "recommendation systems sentiment analysis",
#     "accuracy bias-variance tradeoff",
#     "LSTM attention mechanism",
#     "data visualization exploratory data analysis",
#     "convolutional neural networks recurrent neural networks",
#     "feature selection model evaluation",
#     "deepseek rnns",
#     "support vector machines k-means",
#     "model deployment MLOps",
#     "model monitoring A/B testing",
#     "data mining classification",
#     "GPT feature engineering",
#     "transfer learning few-shot learning",
#     "data preprocessing feature selection",
#     "classification regression",
#     "dropout batch normalization",
#     "probabilistic modeling bayesian inference",
#     "hyperparameter tuning cross-validation",
#     "bayesian inference causal inference",
#     "cross-validation regularization",
#     "underfitting data augmentation",
#     "meta-learning anomaly detection",
#     "self-supervised learning semi-supervised learning",
#     "optimization gradient descent",
#     "regularization dropout",
#     "MLOps model monitoring",
#     "model interpretability explainable AI",
#     "pandas numpy",
#     "numpy data preprocessing",
#     "batch normalization optimization",
#     "sentiment analysis text classification",
#     "federated learning distributed training",
#     "reinforcement learning imitation learning",
#     "semi-supervised learning active learning",
#     "curriculum learning adversarial training",
#     "distributed training quantum machine learning",
#     "A/B testing data visualization",
#     "F1 score accuracy",
#     "data labeling model interpretability",
#     "backpropagation loss functions",
#     "graph neural networks probabilistic modeling",
#     "feature engineering data mining",
#     "transformers BERT",
#     "GANs autoencoders",
#     "active learning online learning",
#     "tensorflow pytorch",
#     "data augmentation model deployment",
#     "k-means decision trees",
#     "gradient boosting support vector machines",
#     "AutoML neural architecture search",
#     "neural architecture search knowledge distillation",
#     "data cleaning data labeling",
#     "regression clustering",
#     "deepseek machinelarning",
#     "attention mechanism hyperparameter tuning",
#     "bias-variance tradeoff overfitting",
#     "online learning incremental learning",
#     "time series analysis recommendation systems"
# ]

keywords_list = [ 
    "danuglipron"
]