---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag
  - name: Print tag
    debug:
      var: tag
  - name: Build frontend container image
    shell: |
      cd /frontend && \
      docker buildx build --platform linux/amd64 -t gcr.io/{{ gcp_project }}/expert-finder-frontend:{{ tag.stdout }} .
    args:
      executable: /bin/bash
  - name: Push frontend image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/expert-finder-frontend:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/expert-finder-frontend:{{ tag.stdout}}
      push: yes
      source: local
  - name: Build api-service container image
    shell: |
      cd /backend && \
      docker buildx build --platform linux/amd64 -t gcr.io/{{ gcp_project }}/expert-finder-backend:{{ tag.stdout }} .
    args:
      executable: /bin/bash
  - name: Push api-service image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/expert-finder-backend:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/expert-finder-backend:{{ tag.stdout}}
      push: yes
      source: local
  - name: "Save docker tag"
    shell: echo {{ tag.stdout}} > .docker-tag
  - name: "Remove all unused containers"
    shell: docker system prune -a