apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expert-finder-cluster-namespace
spec:
  template:
    spec:
      containers:
      - name: backend
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
