name: Backend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        pipenv install --dev
        pipenv install pytest pytest-cov pytest-mock httpx pytest-asyncio
        
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        pipenv install flake8
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Run unit tests
      working-directory: ./backend
      run: |
        pipenv run python -m pytest -m unit -v
        
    - name: Run integration tests
      working-directory: ./backend
      run: |
        pipenv run python -m pytest -m integration -v
        
    - name: Check coverage
      working-directory: ./backend
      run: |
        pipenv run python -m pytest --cov=. --cov-report=xml --cov-report=term-missing
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false
